"""Interfaces the auth use cases require from adapters."""

from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.modules.auth.domain import SessionRecord, User


class AuthRepository(Protocol):
    def user_by_email(self, email: str) -> User | None: ...

    def user_by_id(self, user_id: UUID) -> User | None: ...

    def create_user(self, email: str, password_hash: str | None) -> User: ...

    def identity_user_id(self, provider: str, subject: str) -> UUID | None: ...

    def identity_exists_for_user(self, provider: str, user_id: UUID) -> bool: ...

    def link_identity(self, provider: str, subject: str, user_id: UUID) -> None: ...

    def create_session(self, session: SessionRecord) -> None: ...

    def active_session(self, session_id: UUID) -> SessionRecord | None: ...

    def replace_refresh_token(
        self,
        session_id: UUID,
        previous_token_hash: str,
        token_hash: str,
        expires_at: datetime,
    ) -> bool: ...

    def revoke_session(self, session_id: UUID) -> None: ...


class PasswordManager(Protocol):
    def hash(self, password: str) -> str: ...

    def verify(self, password: str, password_hash: str) -> bool: ...


class TokenManager(Protocol):
    def issue(self, user_id: UUID, session_id: UUID) -> tuple[str, str, datetime]: ...

    def access_claims(self, token: str) -> tuple[UUID, UUID]: ...

    def refresh_claims(self, token: str) -> tuple[UUID, UUID]: ...

    def hash_refresh(self, token: str) -> str: ...
