"""Ports required by user-library interaction use cases."""

from typing import Literal, Protocol
from uuid import UUID

from app.modules.interactions.domain import InteractionStatus, LibraryItem

LibraryCollection = Literal["ratings", "watchlist", "watched", "not-interested"]


class InteractionRepository(Protocol):
    def title_exists(self, title_id: UUID) -> bool: ...

    def rating_exists(self, user_id: UUID, title_id: UUID) -> bool: ...

    def create_rating(self, user_id: UUID, title_id: UUID, value: float) -> None: ...

    def delete_rating(self, user_id: UUID, title_id: UUID) -> None: ...

    def add_watchlist(self, user_id: UUID, title_id: UUID) -> None: ...

    def remove_watchlist(self, user_id: UUID, title_id: UUID) -> None: ...

    def mark_watched(self, user_id: UUID, title_id: UUID) -> None: ...

    def remove_watched(self, user_id: UUID, title_id: UUID) -> None: ...

    def mark_not_interested(self, user_id: UUID, title_id: UUID) -> None: ...

    def remove_not_interested(self, user_id: UUID, title_id: UUID) -> None: ...

    def status(self, user_id: UUID, title_id: UUID) -> InteractionStatus: ...

    def library(self, user_id: UUID, collection: LibraryCollection) -> list[LibraryItem]: ...
